const CAPITALS = [
  // Africa
  { name: "Algiers",            country: "Algeria",                      lat: 36.737,  lng: 3.086   },
  { name: "Luanda",             country: "Angola",                       lat: -8.836,  lng: 13.234  },
  { name: "Porto-Novo",         country: "Benin",                        lat: 6.370,   lng: 2.420   },
  { name: "Gaborone",           country: "Botswana",                     lat: -24.628, lng: 25.913  },
  { name: "Ouagadougou",        country: "Burkina Faso",                 lat: 12.365,  lng: -1.533  },
  { name: "Bujumbura",          country: "Burundi",                      lat: -3.381,  lng: 29.362  },
  { name: "Yaounde",            country: "Cameroon",                     lat: 3.866,   lng: 11.516  },
  { name: "Praia",              country: "Cape Verde",                   lat: 14.933,  lng: -23.513 },
  { name: "Bangui",             country: "Central African Republic",     lat: 4.361,   lng: 18.555  },
  { name: "N'Djamena",          country: "Chad",                         lat: 12.107,  lng: 15.044  },
  { name: "Moroni",             country: "Comoros",                      lat: -11.702, lng: 43.255  },
  { name: "Kinshasa",           country: "Democratic Republic of Congo", lat: -4.322,  lng: 15.322  },
  { name: "Brazzaville",        country: "Republic of Congo",            lat: -4.267,  lng: 15.283  },
  { name: "Djibouti",           country: "Djibouti",                     lat: 11.589,  lng: 43.145  },
  { name: "Cairo",              country: "Egypt",                        lat: 30.061,  lng: 31.249  },
  { name: "Malabo",             country: "Equatorial Guinea",            lat: 3.750,   lng: 8.783   },
  { name: "Asmara",             country: "Eritrea",                      lat: 15.338,  lng: 38.932  },
  { name: "Addis Ababa",        country: "Ethiopia",                     lat: 9.024,   lng: 38.747  },
  { name: "Libreville",         country: "Gabon",                        lat: 0.390,   lng: 9.454   },
  { name: "Banjul",             country: "Gambia",                       lat: 13.454,  lng: -16.579 },
  { name: "Accra",              country: "Ghana",                        lat: 5.560,   lng: -0.205  },
  { name: "Conakry",            country: "Guinea",                       lat: 9.537,   lng: -13.677 },
  { name: "Bissau",             country: "Guinea-Bissau",                lat: 11.863,  lng: -15.598 },
  { name: "Yamoussoukro",       country: "Ivory Coast",                  lat: 6.820,   lng: -5.278  },
  { name: "Nairobi",            country: "Kenya",                        lat: -1.286,  lng: 36.818  },
  { name: "Maseru",             country: "Lesotho",                      lat: -29.316, lng: 27.484  },
  { name: "Monrovia",           country: "Liberia",                      lat: 6.300,   lng: -10.797 },
  { name: "Tripoli",            country: "Libya",                        lat: 32.902,  lng: 13.180  },
  { name: "Antananarivo",       country: "Madagascar",                   lat: -18.914, lng: 47.536  },
  { name: "Lilongwe",           country: "Malawi",                       lat: -13.967, lng: 33.787  },
  { name: "Bamako",             country: "Mali",                         lat: 12.650,  lng: -8.000  },
  { name: "Nouakchott",         country: "Mauritania",                   lat: 18.079,  lng: -15.965 },
  { name: "Port Louis",         country: "Mauritius",                    lat: -20.161, lng: 57.499  },
  { name: "Rabat",              country: "Morocco",                      lat: 34.020,  lng: -6.851  },
  { name: "Maputo",             country: "Mozambique",                   lat: -25.966, lng: 32.589  },
  { name: "Windhoek",           country: "Namibia",                      lat: -22.558, lng: 17.083  },
  { name: "Niamey",             country: "Niger",                        lat: 13.512,  lng: 2.125   },
  { name: "Abuja",              country: "Nigeria",                      lat: 9.072,   lng: 7.399   },
  { name: "Kigali",             country: "Rwanda",                       lat: -1.944,  lng: 30.061  },
  { name: "Sao Tome",           country: "Sao Tome and Principe",        lat: 0.336,   lng: 6.727   },
  { name: "Dakar",              country: "Senegal",                      lat: 14.716,  lng: -17.467 },
  { name: "Victoria",           country: "Seychelles",                   lat: -4.619,  lng: 55.452  },
  { name: "Freetown",           country: "Sierra Leone",                 lat: 8.484,   lng: -13.234 },
  { name: "Mogadishu",          country: "Somalia",                      lat: 2.046,   lng: 45.341  },
  { name: "Pretoria",           country: "South Africa",                 lat: -25.748, lng: 28.188  },
  { name: "Juba",               country: "South Sudan",                  lat: 4.859,   lng: 31.571  },
  { name: "Khartoum",           country: "Sudan",                        lat: 15.551,  lng: 32.532  },
  { name: "Mbabane",            country: "Eswatini",                     lat: -26.318, lng: 31.144  },
  { name: "Dodoma",             country: "Tanzania",                     lat: -6.173,  lng: 35.739  },
  { name: "Lome",               country: "Togo",                         lat: 6.137,   lng: 1.222   },
  { name: "Tunis",              country: "Tunisia",                      lat: 36.819,  lng: 10.166  },
  { name: "Kampala",            country: "Uganda",                       lat: 0.319,   lng: 32.581  },
  { name: "Lusaka",             country: "Zambia",                       lat: -15.417, lng: 28.283  },
  { name: "Harare",             country: "Zimbabwe",                     lat: -17.825, lng: 31.053  },

  // Americas
  { name: "Saint John's",       country: "Antigua and Barbuda",          lat: 17.120,  lng: -61.847 },
  { name: "Buenos Aires",       country: "Argentina",                    lat: -34.601, lng: -58.384 },
  { name: "Nassau",             country: "Bahamas",                      lat: 25.048,  lng: -77.353 },
  { name: "Bridgetown",         country: "Barbados",                     lat: 13.097,  lng: -59.618 },
  { name: "Belmopan",           country: "Belize",                       lat: 17.250,  lng: -88.767 },
  { name: "Sucre",              country: "Bolivia",                      lat: -19.043, lng: -65.259 },
  { name: "Brasilia",           country: "Brazil",                       lat: -15.780, lng: -47.929 },
  { name: "Ottawa",             country: "Canada",                       lat: 45.421,  lng: -75.690 },
  { name: "Santiago",           country: "Chile",                        lat: -33.459, lng: -70.648 },
  { name: "Bogota",             country: "Colombia",                     lat: 4.710,   lng: -74.073 },
  { name: "San Jose",           country: "Costa Rica",                   lat: 9.934,   lng: -84.087 },
  { name: "Havana",             country: "Cuba",                         lat: 23.132,  lng: -82.380 },
  { name: "Roseau",             country: "Dominica",                     lat: 15.301,  lng: -61.387 },
  { name: "Santo Domingo",      country: "Dominican Republic",           lat: 18.483,  lng: -69.930 },
  { name: "Quito",              country: "Ecuador",                      lat: -0.229,  lng: -78.524 },
  { name: "San Salvador",       country: "El Salvador",                  lat: 13.692,  lng: -89.218 },
  { name: "Saint George's",     country: "Grenada",                      lat: 12.052,  lng: -61.752 },
  { name: "Guatemala City",     country: "Guatemala",                    lat: 14.641,  lng: -90.513 },
  { name: "Georgetown",         country: "Guyana",                       lat: 6.800,   lng: -58.155 },
  { name: "Port-au-Prince",     country: "Haiti",                        lat: 18.543,  lng: -72.339 },
  { name: "Tegucigalpa",        country: "Honduras",                     lat: 14.099,  lng: -87.207 },
  { name: "Kingston",           country: "Jamaica",                      lat: 17.997,  lng: -76.793 },
  { name: "Mexico City",        country: "Mexico",                       lat: 19.433,  lng: -99.133 },
  { name: "Managua",            country: "Nicaragua",                    lat: 12.136,  lng: -86.278 },
  { name: "Panama City",        country: "Panama",                       lat: 8.994,   lng: -79.519 },
  { name: "Asuncion",           country: "Paraguay",                     lat: -25.282, lng: -57.637 },
  { name: "Lima",               country: "Peru",                         lat: -12.046, lng: -77.043 },
  { name: "Basseterre",         country: "Saint Kitts and Nevis",        lat: 17.296,  lng: -62.728 },
  { name: "Castries",           country: "Saint Lucia",                  lat: 14.010,  lng: -60.987 },
  { name: "Kingstown",          country: "Saint Vincent and the Grenadines", lat: 13.160, lng: -61.225 },
  { name: "Paramaribo",         country: "Suriname",                     lat: 5.866,   lng: -55.167 },
  { name: "Port of Spain",      country: "Trinidad and Tobago",          lat: 10.652,  lng: -61.519 },
  { name: "Montevideo",         country: "Uruguay",                      lat: -34.857, lng: -56.171 },
  { name: "Washington D.C.",    country: "United States",                lat: 38.907,  lng: -77.037 },
  { name: "Caracas",            country: "Venezuela",                    lat: 10.491,  lng: -66.902 },

  // Asia
  { name: "Kabul",              country: "Afghanistan",                  lat: 34.525,  lng: 69.178  },
  { name: "Yerevan",            country: "Armenia",                      lat: 40.181,  lng: 44.514  },
  { name: "Baku",               country: "Azerbaijan",                   lat: 40.409,  lng: 49.867  },
  { name: "Manama",             country: "Bahrain",                      lat: 26.215,  lng: 50.586  },
  { name: "Dhaka",              country: "Bangladesh",                   lat: 23.723,  lng: 90.408  },
  { name: "Thimphu",            country: "Bhutan",                       lat: 27.472,  lng: 89.639  },
  { name: "Bandar Seri Begawan",country: "Brunei",                       lat: 4.890,   lng: 114.942 },
  { name: "Phnom Penh",         country: "Cambodia",                     lat: 11.562,  lng: 104.916 },
  { name: "Beijing",            country: "China",                        lat: 39.916,  lng: 116.383 },
  { name: "Nicosia",            country: "Cyprus",                       lat: 35.185,  lng: 33.382  },
  { name: "Tbilisi",            country: "Georgia",                      lat: 41.694,  lng: 44.833  },
  { name: "New Delhi",          country: "India",                        lat: 28.614,  lng: 77.202  },
  { name: "Jakarta",            country: "Indonesia",                    lat: -6.211,  lng: 106.845 },
  { name: "Tehran",             country: "Iran",                         lat: 35.694,  lng: 51.421  },
  { name: "Baghdad",            country: "Iraq",                         lat: 33.341,  lng: 44.401  },
  { name: "Jerusalem",          country: "Israel",                       lat: 31.771,  lng: 35.217  },
  { name: "Tokyo",              country: "Japan",                        lat: 35.682,  lng: 139.692 },
  { name: "Amman",              country: "Jordan",                       lat: 31.956,  lng: 35.945  },
  { name: "Astana",             country: "Kazakhstan",                   lat: 51.180,  lng: 71.446  },
  { name: "Kuwait City",        country: "Kuwait",                       lat: 29.375,  lng: 47.977  },
  { name: "Bishkek",            country: "Kyrgyzstan",                   lat: 42.871,  lng: 74.594  },
  { name: "Vientiane",          country: "Laos",                         lat: 17.975,  lng: 102.633 },
  { name: "Beirut",             country: "Lebanon",                      lat: 33.872,  lng: 35.508  },
  { name: "Kuala Lumpur",       country: "Malaysia",                     lat: 3.147,   lng: 101.696 },
  { name: "Male",               country: "Maldives",                     lat: 4.175,   lng: 73.509  },
  { name: "Ulaanbaatar",        country: "Mongolia",                     lat: 47.886,  lng: 106.906 },
  { name: "Naypyidaw",          country: "Myanmar",                      lat: 19.745,  lng: 96.129  },
  { name: "Kathmandu",          country: "Nepal",                        lat: 27.717,  lng: 85.318  },
  { name: "Pyongyang",          country: "North Korea",                  lat: 39.039,  lng: 125.762 },
  { name: "Muscat",             country: "Oman",                         lat: 23.614,  lng: 58.593  },
  { name: "Islamabad",          country: "Pakistan",                     lat: 33.729,  lng: 73.093  },
  { name: "Manila",             country: "Philippines",                  lat: 14.599,  lng: 120.984 },
  { name: "Doha",               country: "Qatar",                        lat: 25.286,  lng: 51.534  },
  { name: "Riyadh",             country: "Saudi Arabia",                 lat: 24.687,  lng: 46.722  },
  { name: "Singapore",          country: "Singapore",                    lat: 1.352,   lng: 103.820 },
  { name: "Seoul",              country: "South Korea",                  lat: 37.566,  lng: 126.978 },
  { name: "Colombo",            country: "Sri Lanka",                    lat: 6.927,   lng: 79.861  },
  { name: "Damascus",           country: "Syria",                        lat: 33.510,  lng: 36.291  },
  { name: "Taipei",             country: "Taiwan",                       lat: 25.047,  lng: 121.517 },
  { name: "Dushanbe",           country: "Tajikistan",                   lat: 38.559,  lng: 68.773  },
  { name: "Bangkok",            country: "Thailand",                     lat: 13.754,  lng: 100.502 },
  { name: "Dili",               country: "Timor-Leste",                  lat: -8.556,  lng: 125.578 },
  { name: "Ankara",             country: "Turkey",                       lat: 39.933,  lng: 32.860  },
  { name: "Ashgabat",           country: "Turkmenistan",                 lat: 37.960,  lng: 58.326  },
  { name: "Abu Dhabi",          country: "United Arab Emirates",         lat: 24.466,  lng: 54.366  },
  { name: "Tashkent",           country: "Uzbekistan",                   lat: 41.299,  lng: 69.240  },
  { name: "Hanoi",              country: "Vietnam",                      lat: 21.028,  lng: 105.854 },
  { name: "Sanaa",              country: "Yemen",                        lat: 15.369,  lng: 44.191  },

  // Europe
  { name: "Tirana",             country: "Albania",                      lat: 41.330,  lng: 19.831  },
  { name: "Andorra la Vella",   country: "Andorra",                      lat: 42.506,  lng: 1.521   },
  { name: "Vienna",             country: "Austria",                      lat: 48.208,  lng: 16.373  },
  { name: "Minsk",              country: "Belarus",                      lat: 53.904,  lng: 27.561  },
  { name: "Brussels",           country: "Belgium",                      lat: 50.851,  lng: 4.351   },
  { name: "Sarajevo",           country: "Bosnia and Herzegovina",       lat: 43.848,  lng: 18.356  },
  { name: "Sofia",              country: "Bulgaria",                     lat: 42.698,  lng: 23.322  },
  { name: "Zagreb",             country: "Croatia",                      lat: 45.815,  lng: 15.982  },
  { name: "Prague",             country: "Czech Republic",               lat: 50.088,  lng: 14.421  },
  { name: "Copenhagen",         country: "Denmark",                      lat: 55.676,  lng: 12.568  },
  { name: "Tallinn",            country: "Estonia",                      lat: 59.437,  lng: 24.753  },
  { name: "Helsinki",           country: "Finland",                      lat: 60.169,  lng: 24.935  },
  { name: "Paris",              country: "France",                       lat: 48.857,  lng: 2.351   },
  { name: "Berlin",             country: "Germany",                      lat: 52.520,  lng: 13.405  },
  { name: "Athens",             country: "Greece",                       lat: 37.983,  lng: 23.727  },
  { name: "Budapest",           country: "Hungary",                      lat: 47.498,  lng: 19.040  },
  { name: "Reykjavik",          country: "Iceland",                      lat: 64.135,  lng: -21.895 },
  { name: "Dublin",             country: "Ireland",                      lat: 53.331,  lng: -6.249  },
  { name: "Rome",               country: "Italy",                        lat: 41.902,  lng: 12.496  },
  { name: "Pristina",           country: "Kosovo",                       lat: 42.662,  lng: 21.166  },
  { name: "Riga",               country: "Latvia",                       lat: 56.946,  lng: 24.106  },
  { name: "Vaduz",              country: "Liechtenstein",                lat: 47.141,  lng: 9.521   },
  { name: "Vilnius",            country: "Lithuania",                    lat: 54.687,  lng: 25.280  },
  { name: "Luxembourg City",    country: "Luxembourg",                   lat: 49.612,  lng: 6.130   },
  { name: "Valletta",           country: "Malta",                        lat: 35.899,  lng: 14.514  },
  { name: "Chisinau",           country: "Moldova",                      lat: 47.005,  lng: 28.858  },
  { name: "Monaco",             country: "Monaco",                       lat: 43.731,  lng: 7.420   },
  { name: "Podgorica",          country: "Montenegro",                   lat: 42.441,  lng: 19.262  },
  { name: "Amsterdam",          country: "Netherlands",                  lat: 52.374,  lng: 4.890   },
  { name: "Skopje",             country: "North Macedonia",              lat: 41.997,  lng: 21.428  },
  { name: "Oslo",               country: "Norway",                       lat: 59.911,  lng: 10.752  },
  { name: "Warsaw",             country: "Poland",                       lat: 52.230,  lng: 21.012  },
  { name: "Lisbon",             country: "Portugal",                     lat: 38.717,  lng: -9.139  },
  { name: "Bucharest",          country: "Romania",                      lat: 44.426,  lng: 26.103  },
  { name: "Moscow",             country: "Russia",                       lat: 55.751,  lng: 37.618  },
  { name: "San Marino",         country: "San Marino",                   lat: 43.932,  lng: 12.449  },
  { name: "Belgrade",           country: "Serbia",                       lat: 44.804,  lng: 20.465  },
  { name: "Bratislava",         country: "Slovakia",                     lat: 48.148,  lng: 17.107  },
  { name: "Ljubljana",          country: "Slovenia",                     lat: 46.051,  lng: 14.506  },
  { name: "Madrid",             country: "Spain",                        lat: 40.417,  lng: -3.704  },
  { name: "Stockholm",          country: "Sweden",                       lat: 59.334,  lng: 18.063  },
  { name: "Bern",               country: "Switzerland",                  lat: 46.948,  lng: 7.448   },
  { name: "Kyiv",               country: "Ukraine",                      lat: 50.450,  lng: 30.523  },
  { name: "London",             country: "United Kingdom",               lat: 51.507,  lng: -0.128  },
  { name: "Vatican City",       country: "Vatican City",                 lat: 41.902,  lng: 12.453  },

  // Oceania
  { name: "Canberra",           country: "Australia",                    lat: -35.282, lng: 149.129 },
  { name: "Suva",               country: "Fiji",                         lat: -18.142, lng: 178.441 },
  { name: "South Tarawa",       country: "Kiribati",                     lat: 1.328,   lng: 172.979 },
  { name: "Majuro",             country: "Marshall Islands",             lat: 7.089,   lng: 171.380 },
  { name: "Palikir",            country: "Micronesia",                   lat: 6.921,   lng: 158.161 },
  { name: "Yaren",              country: "Nauru",                        lat: -0.546,  lng: 166.921 },
  { name: "Wellington",         country: "New Zealand",                  lat: -41.286, lng: 174.776 },
  { name: "Ngerulmud",          country: "Palau",                        lat: 7.500,   lng: 134.624 },
  { name: "Port Moresby",       country: "Papua New Guinea",             lat: -9.443,  lng: 147.180 },
  { name: "Apia",               country: "Samoa",                        lat: -13.833, lng: -171.768 },
  { name: "Honiara",            country: "Solomon Islands",              lat: -9.427,  lng: 160.053 },
  { name: "Nuku'alofa",         country: "Tonga",                        lat: -21.136, lng: -175.217 },
  { name: "Funafuti",           country: "Tuvalu",                       lat: -8.520,  lng: 179.198 },
  { name: "Port Vila",          country: "Vanuatu",                      lat: -17.733, lng: 168.322 },
];
